import type { CaptionTrack } from "../types/transcript";

type RawCaptionTrack = {
  baseUrl?: string;
  name?: { simpleText?: string; runs?: Array<{ text?: string }> };
  languageCode?: string;
  kind?: string;
  vssId?: string;
};

type MaybePlayerResponse = {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: RawCaptionTrack[];
    };
  };
};

export function extractCaptionTracks(playerResponse: unknown): CaptionTrack[] {
  const response = playerResponse as MaybePlayerResponse | null;
  const rawTracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (!Array.isArray(rawTracks)) {
    return [];
  }

  return rawTracks
    .map((track): CaptionTrack | null => {
      if (!track.baseUrl || !track.languageCode) {
        return null;
      }

      const name =
        track.name?.simpleText ||
        track.name?.runs?.map((run) => run.text ?? "").join("") ||
        track.languageCode;

      return {
        baseUrl: track.baseUrl,
        name,
        languageCode: track.languageCode,
        kind: track.kind,
        isAutoGenerated: track.kind === "asr" || track.vssId?.startsWith("a.") === true
      };
    })
    .filter((track): track is CaptionTrack => Boolean(track));
}

