import type { CaptionTrack } from "../types/transcript";

export const PREFERRED_LANGUAGES = ["zh-TW", "zh-Hant", "zh", "en", "ja"];

export function selectBestTrack(tracks: CaptionTrack[], preferredLanguages = PREFERRED_LANGUAGES): CaptionTrack | null {
  const manualTracks = tracks.filter((track) => !track.isAutoGenerated);
  const autoTracks = tracks.filter((track) => track.isAutoGenerated);
  const candidates = [...manualTracks, ...autoTracks];

  for (const language of preferredLanguages) {
    const exact = candidates.find((track) => track.languageCode === language);
    if (exact) return exact;

    const baseLanguage = language.split("-")[0];
    const loose = candidates.find((track) => track.languageCode.split("-")[0] === baseLanguage);
    if (loose) return loose;
  }

  return candidates[0] ?? null;
}

