import { formatTimestamp } from "./time";
import type { CaptionTrack, MarkdownFormat, TranscriptPayload } from "../types/transcript";

export function formatTranscriptMarkdown(payload: TranscriptPayload, format: MarkdownFormat): string {
  switch (format) {
    case "plain-text":
      return formatPlainText(payload);
    case "timestamp-list":
      return formatTimestampList(payload);
    case "ai-prompt":
    default:
      return formatAiPrompt(payload);
  }
}

function formatAiPrompt(payload: TranscriptPayload): string {
  const captionType = getCaptionType(payload.selectedTrack);

  return [
    "# YouTube Transcript",
    "",
    `Title: ${payload.video.title}`,
    `URL: ${payload.video.url}`,
    `Language: ${payload.selectedTrack?.languageCode ?? "unknown"}`,
    `Caption type: ${captionType}`,
    `Captured at: ${payload.video.capturedAt}`,
    "",
    "Please summarize the following transcript:",
    "",
    "---",
    "",
    ...payload.segments.map((segment) => `[${formatTimestamp(segment.startSec)}] ${segment.text}`)
  ].join("\n");
}

function formatPlainText(payload: TranscriptPayload): string {
  return [
    `# ${payload.video.title}`,
    "",
    `Source: ${payload.video.url}`,
    "",
    "## Transcript",
    "",
    ...payload.segments.map((segment) => segment.text)
  ].join("\n\n");
}

function formatTimestampList(payload: TranscriptPayload): string {
  return [
    `# ${payload.video.title}`,
    "",
    `Source: ${payload.video.url}`,
    "",
    "## Transcript",
    "",
    ...payload.segments.map((segment) => `- [${formatTimestamp(segment.startSec)}] ${segment.text}`)
  ].join("\n");
}

function getCaptionType(track: CaptionTrack | null): string {
  if (!track) return "unknown";
  return track.isAutoGenerated ? "auto-generated" : "manual";
}

