export interface VideoInfo {
  videoId: string;
  title: string;
  url: string;
  capturedAt: string;
}

export interface CaptionTrack {
  baseUrl: string;
  name: string;
  languageCode: string;
  kind?: string;
  isAutoGenerated: boolean;
}

export interface TranscriptSegment {
  startSec: number;
  durationSec: number | null;
  text: string;
  source: "caption-track" | "transcript-panel" | "speech-to-text";
  languageCode?: string;
}

export interface TranscriptPayload {
  video: VideoInfo;
  selectedTrack: CaptionTrack | null;
  segments: TranscriptSegment[];
}

export type MarkdownFormat = "ai-prompt" | "timestamp-list" | "plain-text";

export type SttStatus = "idle" | "recording" | "transcribing";

export type SttProvider = "gemini" | "openai";

export interface SttResult {
  text: string;
  recordedAt: string;
}

export interface StoredSttResult extends SttResult {
  id: string;
}

export interface ExtractPageDataResponse {
  video: VideoInfo;
  playerResponse: unknown | null;
}

export interface FetchCaptionRequest {
  track: CaptionTrack;
}

export interface TriggerCaptionRequest {
  languageCode?: string;
}

export interface FetchCapturedCaptionRequest {
  tabId: number;
  languageCode?: string;
}

export interface FetchCaptionResponse {
  raw: string;
  format: "json3" | "xml" | "srv3" | "vtt" | "unknown";
}

export interface FetchTranscriptPanelResponse {
  segments: TranscriptSegment[];
}

export interface FetchInnertubeCaptionRequest {
  videoId: string;
  preferredLanguageCode?: string;
}
